Add auth tokens
EABModel/backend pull request #11
Opened 2021-05-29 20:16 UTC by slecaros

aded routes:

- [GET] /user/auth: given a refresh token return a new token

create and login return:
- user
- refresh_token
- token

2021-05-30 16:59 UTC, dasolari requested changes
Deje algunos comentarios que es necesario cambiarlos.

2021-05-30 16:59 UTC, dasolari commented on my_app/routes/product.py
> +@cache.cached(timeout=50)
Sacar `cache` de acá ya que es method `POST`.

2021-05-30 16:59 UTC, dasolari commented on my_app/routes/product.py
> +@cache.cached(timeout=50)
Lo mismo de arriba aca

2021-05-30 16:59 UTC, dasolari commented on my_app/utils/auth.py
> +            if user and user.sessionType == 'ADMIN':
El nombre es `ADMINISTRATOR`, para cambiarlo.

2021-06-27 15:21 UTC, Fenho approved these changes

2021-06-27 15:21 UTC, Fenho commented on my_app/__init__.py
> +# app.config.update(
Comentario

2021-06-27 15:21 UTC, Fenho commented on my_app/routes/user.py
> +        # return make_response(jsonify(user), 201)
Comentario

2021-06-27 15:21 UTC, merged