Agregando tabla call y rutas create y agregar rating
EABModel/backend pull request #13
Opened 2021-05-30 20:34 UTC by fivaldivia

## What
Se implemento tabla Call para las videollamadas y las rutas de create y agregar rating.

## Why
Luego de una videollamada debe realizarse una encuesta de servicio al cliente.

## How
Se crea la tabla Call y ruta calls/new-call para crear una llamada y calls/callId para editar el atributo rating ce Call luego de que el cliente termine su videollamada. Este rating es un Float.

Nota: falta probarlo con frontend en conjunto

2021-07-04 22:49 UTC, dasolari requested changes
Super! Pero hay algunas cosas que hay que cambiar!

2021-07-04 22:49 UTC, dasolari commented on Dockerfile
> -CMD ["flask", "run"]
OJO 👀  @fivaldivia que cambiaste el dockerfile.

2021-07-04 22:49 UTC, dasolari commented on my_app/__init__.py
> +cors = CORS(app, resources={r"/*": {"origins": "*"}})
Entonces esta coma si estaba de más. 👍

2021-07-04 22:49 UTC, dasolari commented on requirements.txt
> +psycopg2-binary
Esto tampoco debería estar. Esto es solo para que te funcione a ti @fivaldivia.

2021-07-04 22:49 UTC, dasolari commented on my_app/routes/product.py
> +            employeeId=row['employeeId'],
¿Por qué este cambio?

2021-07-05 14:44 UTC, fivaldivia commented on Dockerfile
> -CMD ["flask", "run"]
Ufff se me olvido cambiarlo

2021-07-05 14:45 UTC, fivaldivia commented on my_app/routes/product.py
> +            employeeId=row['employeeId'],
Si, probablemente es porque esta hace mucho la rama

2021-07-05 14:46 UTC, fivaldivia commented on Dockerfile
> -CMD ["flask", "run"]
Ufff se me olvido cambiarlo

2021-07-05 14:53 UTC, dasolari commented on requirements.txt
> +psycopg2-binary
Faltaría esto nomás para poder mergear.

2021-07-05 15:01 UTC, fivaldivia commented on requirements.txt
> +psycopg2-binary
Ya lo cambié..No te aparece?

2021-07-05 15:22 UTC, Fenho approved these changes
👍

2021-07-05 15:23 UTC, dasolari commented on requirements.txt
> +psycopg2-binary
Ah si, ya esta.

2021-07-05 15:23 UTC, dasolari approved these changes
Todo listo entonces. Se aprueban los cambios 👍

2021-07-05 15:26 UTC, merged